package tn.tfar.fanconi.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FicheAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheAllPropertiesEquals(Fiche expected, Fiche actual) {
        assertFicheAutoGeneratedPropertiesEquals(expected, actual);
        assertFicheAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheAllUpdatablePropertiesEquals(Fiche expected, Fiche actual) {
        assertFicheUpdatableFieldsEquals(expected, actual);
        assertFicheUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheAutoGeneratedPropertiesEquals(Fiche expected, Fiche actual) {
        assertThat(expected)
            .as("Verify Fiche auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheUpdatableFieldsEquals(Fiche expected, Fiche actual) {
        assertThat(expected)
            .as("Verify Fiche relevant properties")
            .satisfies(e -> assertThat(e.getnDossier()).as("check nDossier").isEqualTo(actual.getnDossier()))
            .satisfies(e -> assertThat(e.getDateDiagnostic()).as("check dateDiagnostic").isEqualTo(actual.getDateDiagnostic()))
            .satisfies(e -> assertThat(e.getDateEnregistrement()).as("check dateEnregistrement").isEqualTo(actual.getDateEnregistrement()))
            .satisfies(e -> assertThat(e.getMedecin()).as("check medecin").isEqualTo(actual.getMedecin()))
            .satisfies(e -> assertThat(e.getHopital()).as("check hopital").isEqualTo(actual.getHopital()))
            .satisfies(e -> assertThat(e.getService()).as("check service").isEqualTo(actual.getService()))
            .satisfies(e -> assertThat(e.getDegConsang()).as("check degConsang").isEqualTo(actual.getDegConsang()))
            .satisfies(e -> assertThat(e.getPlaceEnfant()).as("check placeEnfant").isEqualTo(actual.getPlaceEnfant()))
            .satisfies(e -> assertThat(e.getNbVivant()).as("check nbVivant").isEqualTo(actual.getNbVivant()))
            .satisfies(e -> assertThat(e.getNbMort()).as("check nbMort").isEqualTo(actual.getNbMort()))
            .satisfies(e -> assertThat(e.getMortNe()).as("check mortNe").isEqualTo(actual.getMortNe()))
            .satisfies(e -> assertThat(e.getAvortement()).as("check avortement").isEqualTo(actual.getAvortement()))
            .satisfies(e -> assertThat(e.getCousin()).as("check cousin").isEqualTo(actual.getCousin()))
            .satisfies(e -> assertThat(e.getMembre()).as("check membre").isEqualTo(actual.getMembre()))
            .satisfies(e -> assertThat(e.getArbregenealogique()).as("check arbregenealogique").isEqualTo(actual.getArbregenealogique()))
            .satisfies(e ->
                assertThat(e.getArbregenealogiqueContentType())
                    .as("check arbregenealogique contenty type")
                    .isEqualTo(actual.getArbregenealogiqueContentType())
            )
            .satisfies(e ->
                assertThat(e.getArbregenealogiquecancer())
                    .as("check arbregenealogiquecancer")
                    .isEqualTo(actual.getArbregenealogiquecancer())
            )
            .satisfies(e ->
                assertThat(e.getArbregenealogiquecancerContentType())
                    .as("check arbregenealogiquecancer contenty type")
                    .isEqualTo(actual.getArbregenealogiquecancerContentType())
            )
            .satisfies(e -> assertThat(e.getSyndromeAnemique()).as("check syndromeAnemique").isEqualTo(actual.getSyndromeAnemique()))
            .satisfies(e -> assertThat(e.getSyndromeHem()).as("check syndromeHem").isEqualTo(actual.getSyndromeHem()))
            .satisfies(e -> assertThat(e.getSyndromeInf()).as("check syndromeInf").isEqualTo(actual.getSyndromeInf()))
            .satisfies(e -> assertThat(e.getDecouverteFort()).as("check decouverteFort").isEqualTo(actual.getDecouverteFort()))
            .satisfies(e -> assertThat(e.getEnqueteFam()).as("check enqueteFam").isEqualTo(actual.getEnqueteFam()))
            .satisfies(e -> assertThat(e.getTypeCancer()).as("check typeCancer").isEqualTo(actual.getTypeCancer()))
            .satisfies(e -> assertThat(e.getCancer()).as("check cancer").isEqualTo(actual.getCancer()))
            .satisfies(e -> assertThat(e.getTailleNaiss()).as("check tailleNaiss").isEqualTo(actual.getTailleNaiss()))
            .satisfies(e -> assertThat(e.getPoidsNaiss()).as("check poidsNaiss").isEqualTo(actual.getPoidsNaiss()))
            .satisfies(e -> assertThat(e.getHypotrophie()).as("check hypotrophie").isEqualTo(actual.getHypotrophie()))
            .satisfies(e -> assertThat(e.getTroubleCroi()).as("check troubleCroi").isEqualTo(actual.getTroubleCroi()))
            .satisfies(e -> assertThat(e.getaAgeChDiag()).as("check aAgeChDiag").isEqualTo(actual.getaAgeChDiag()))
            .satisfies(e -> assertThat(e.getmAgeChDiag()).as("check mAgeChDiag").isEqualTo(actual.getmAgeChDiag()))
            .satisfies(e -> assertThat(e.getaAgeOssDiag()).as("check aAgeOssDiag").isEqualTo(actual.getaAgeOssDiag()))
            .satisfies(e -> assertThat(e.getmAgeOssDiag()).as("check mAgeOssDiag").isEqualTo(actual.getmAgeOssDiag()))
            .satisfies(e -> assertThat(e.getAgeRetard()).as("check ageRetard").isEqualTo(actual.getAgeRetard()))
            .satisfies(e -> assertThat(e.getPoids()).as("check poids").isEqualTo(actual.getPoids()))
            .satisfies(e -> assertThat(e.getPoidsDS()).as("check poidsDS").isEqualTo(actual.getPoidsDS()))
            .satisfies(e -> assertThat(e.getTaille()).as("check taille").isEqualTo(actual.getTaille()))
            .satisfies(e -> assertThat(e.getTailleDS()).as("check tailleDS").isEqualTo(actual.getTailleDS()))
            .satisfies(e -> assertThat(e.getAtteinteCut()).as("check atteinteCut").isEqualTo(actual.getAtteinteCut()))
            .satisfies(e -> assertThat(e.getTacheCaf()).as("check tacheCaf").isEqualTo(actual.getTacheCaf()))
            .satisfies(e -> assertThat(e.getVentre()).as("check ventre").isEqualTo(actual.getVentre()))
            .satisfies(e -> assertThat(e.getMembreSup()).as("check membreSup").isEqualTo(actual.getMembreSup()))
            .satisfies(e -> assertThat(e.getMembreInf()).as("check membreInf").isEqualTo(actual.getMembreInf()))
            .satisfies(e -> assertThat(e.getVisage()).as("check visage").isEqualTo(actual.getVisage()))
            .satisfies(e -> assertThat(e.getThorax()).as("check thorax").isEqualTo(actual.getThorax()))
            .satisfies(e -> assertThat(e.getdOS()).as("check dOS").isEqualTo(actual.getdOS()))
            .satisfies(e -> assertThat(e.getHyperPig()).as("check hyperPig").isEqualTo(actual.getHyperPig()))
            .satisfies(e -> assertThat(e.getHypochromique()).as("check hypochromique").isEqualTo(actual.getHypochromique()))
            .satisfies(e -> assertThat(e.getCouleurPeau()).as("check couleurPeau").isEqualTo(actual.getCouleurPeau()))
            .satisfies(e -> assertThat(e.getAutreAtCut()).as("check autreAtCut").isEqualTo(actual.getAutreAtCut()))
            .satisfies(e -> assertThat(e.getAtteinteTete()).as("check atteinteTete").isEqualTo(actual.getAtteinteTete()))
            .satisfies(e -> assertThat(e.getMicrocephalie()).as("check microcephalie").isEqualTo(actual.getMicrocephalie()))
            .satisfies(e -> assertThat(e.getMicrophtalmie()).as("check microphtalmie").isEqualTo(actual.getMicrophtalmie()))
            .satisfies(e -> assertThat(e.getFacieTrig()).as("check facieTrig").isEqualTo(actual.getFacieTrig()))
            .satisfies(e -> assertThat(e.getTraitsFin()).as("check traitsFin").isEqualTo(actual.getTraitsFin()))
            .satisfies(e -> assertThat(e.getAutreAtTete()).as("check autreAtTete").isEqualTo(actual.getAutreAtTete()))
            .satisfies(e ->
                assertThat(e.getEmpreintedigitiforme()).as("check empreintedigitiforme").isEqualTo(actual.getEmpreintedigitiforme())
            )
            .satisfies(e -> assertThat(e.getMalUro()).as("check malUro").isEqualTo(actual.getMalUro()))
            .satisfies(e -> assertThat(e.getuIV()).as("check uIV").isEqualTo(actual.getuIV()))
            .satisfies(e -> assertThat(e.getEcho()).as("check echo").isEqualTo(actual.getEcho()))
            .satisfies(e -> assertThat(e.getReinEctop()).as("check reinEctop").isEqualTo(actual.getReinEctop()))
            .satisfies(e -> assertThat(e.getSiegeEctopie()).as("check siegeEctopie").isEqualTo(actual.getSiegeEctopie()))
            .satisfies(e -> assertThat(e.getReinFerChev()).as("check reinFerChev").isEqualTo(actual.getReinFerChev()))
            .satisfies(e -> assertThat(e.getPetitRein()).as("check petitRein").isEqualTo(actual.getPetitRein()))
            .satisfies(e -> assertThat(e.getReinUnique()).as("check reinUnique").isEqualTo(actual.getReinUnique()))
            .satisfies(e -> assertThat(e.getEctopTest()).as("check ectopTest").isEqualTo(actual.getEctopTest()))
            .satisfies(e -> assertThat(e.getVergeInsuf()).as("check vergeInsuf").isEqualTo(actual.getVergeInsuf()))
            .satisfies(e -> assertThat(e.getAutreAnomVerge()).as("check autreAnomVerge").isEqualTo(actual.getAutreAnomVerge()))
            .satisfies(e -> assertThat(e.getRetardPubertaire()).as("check retardPubertaire").isEqualTo(actual.getRetardPubertaire()))
            .satisfies(e -> assertThat(e.getmTanner()).as("check mTanner").isEqualTo(actual.getmTanner()))
            .satisfies(e -> assertThat(e.getpTanner()).as("check pTanner").isEqualTo(actual.getpTanner()))
            .satisfies(e -> assertThat(e.gettTanner()).as("check tTanner").isEqualTo(actual.gettTanner()))
            .satisfies(e -> assertThat(e.getAnomUrin()).as("check anomUrin").isEqualTo(actual.getAnomUrin()))
            .satisfies(e -> assertThat(e.getTypeAnomUrin()).as("check typeAnomUrin").isEqualTo(actual.getTypeAnomUrin()))
            .satisfies(e -> assertThat(e.getAtteinteOss()).as("check atteinteOss").isEqualTo(actual.getAtteinteOss()))
            .satisfies(e -> assertThat(e.getRadiosfaites()).as("check radiosfaites").isEqualTo(actual.getRadiosfaites()))
            .satisfies(e -> assertThat(e.getAnomPouce()).as("check anomPouce").isEqualTo(actual.getAnomPouce()))
            .satisfies(e -> assertThat(e.getSurnumerarie()).as("check surnumerarie").isEqualTo(actual.getSurnumerarie()))
            .satisfies(e -> assertThat(e.getAgenesiePouce()).as("check agenesiePouce").isEqualTo(actual.getAgenesiePouce()))
            .satisfies(e -> assertThat(e.getBifide()).as("check bifide").isEqualTo(actual.getBifide()))
            .satisfies(e -> assertThat(e.getHypoPouce()).as("check hypoPouce").isEqualTo(actual.getHypoPouce()))
            .satisfies(e -> assertThat(e.getAspectPouce()).as("check aspectPouce").isEqualTo(actual.getAspectPouce()))
            .satisfies(e -> assertThat(e.getHypoEminence()).as("check hypoEminence").isEqualTo(actual.getHypoEminence()))
            .satisfies(e -> assertThat(e.getAbsenceRadial()).as("check absenceRadial").isEqualTo(actual.getAbsenceRadial()))
            .satisfies(e -> assertThat(e.getPouceBas()).as("check pouceBas").isEqualTo(actual.getPouceBas()))
            .satisfies(e -> assertThat(e.getAutreAnomPouce()).as("check autreAnomPouce").isEqualTo(actual.getAutreAnomPouce()))
            .satisfies(e -> assertThat(e.getAnomAutDoigts()).as("check anomAutDoigts").isEqualTo(actual.getAnomAutDoigts()))
            .satisfies(e -> assertThat(e.getCourtstrapus()).as("check courtstrapus").isEqualTo(actual.getCourtstrapus()))
            .satisfies(e -> assertThat(e.getSyndactylie()).as("check syndactylie").isEqualTo(actual.getSyndactylie()))
            .satisfies(e -> assertThat(e.getAutreAnomDoigts()).as("check autreAnomDoigts").isEqualTo(actual.getAutreAnomDoigts()))
            .satisfies(e -> assertThat(e.getAnomalieos()).as("check anomalieos").isEqualTo(actual.getAnomalieos()))
            .satisfies(e -> assertThat(e.getAgenesieRadius()).as("check agenesieRadius").isEqualTo(actual.getAgenesieRadius()))
            .satisfies(e ->
                assertThat(e.getAutreanomalieMembresup()).as("check autreanomalieMembresup").isEqualTo(actual.getAutreanomalieMembresup())
            )
            .satisfies(e -> assertThat(e.getAnomOrteil()).as("check anomOrteil").isEqualTo(actual.getAnomOrteil()))
            .satisfies(e -> assertThat(e.getPreciseAnomOrt()).as("check preciseAnomOrt").isEqualTo(actual.getPreciseAnomOrt()))
            .satisfies(e -> assertThat(e.getlCH()).as("check lCH").isEqualTo(actual.getlCH()))
            .satisfies(e ->
                assertThat(e.getAutreanomalieMembreinf()).as("check autreanomalieMembreinf").isEqualTo(actual.getAutreanomalieMembreinf())
            )
            .satisfies(e -> assertThat(e.getAnomRachis()).as("check anomRachis").isEqualTo(actual.getAnomRachis()))
            .satisfies(e -> assertThat(e.getPreciseAnomRac()).as("check preciseAnomRac").isEqualTo(actual.getPreciseAnomRac()))
            .satisfies(e -> assertThat(e.getAutreAnomOss()).as("check autreAnomOss").isEqualTo(actual.getAutreAnomOss()))
            .satisfies(e -> assertThat(e.getAnomNeuro()).as("check anomNeuro").isEqualTo(actual.getAnomNeuro()))
            .satisfies(e -> assertThat(e.getRetardMent()).as("check retardMent").isEqualTo(actual.getRetardMent()))
            .satisfies(e -> assertThat(e.getHypoacousie()).as("check hypoacousie").isEqualTo(actual.getHypoacousie()))
            .satisfies(e -> assertThat(e.getStrabisme()).as("check strabisme").isEqualTo(actual.getStrabisme()))
            .satisfies(e ->
                assertThat(e.getPerformanceScolaire()).as("check performanceScolaire").isEqualTo(actual.getPerformanceScolaire())
            )
            .satisfies(e ->
                assertThat(e.getAutreanomalieneurologique())
                    .as("check autreanomalieneurologique")
                    .isEqualTo(actual.getAutreanomalieneurologique())
            )
            .satisfies(e -> assertThat(e.getAnomCardVas()).as("check anomCardVas").isEqualTo(actual.getAnomCardVas()))
            .satisfies(e -> assertThat(e.getEchoCoeur()).as("check echoCoeur").isEqualTo(actual.getEchoCoeur()))
            .satisfies(e -> assertThat(e.getPreciseAnomCardio()).as("check preciseAnomCardio").isEqualTo(actual.getPreciseAnomCardio()))
            .satisfies(e -> assertThat(e.getAnomDig()).as("check anomDig").isEqualTo(actual.getAnomDig()))
            .satisfies(e -> assertThat(e.getPreciseAnomDig()).as("check preciseAnomDig").isEqualTo(actual.getPreciseAnomDig()))
            .satisfies(e -> assertThat(e.getEndocrinopathie()).as("check endocrinopathie").isEqualTo(actual.getEndocrinopathie()))
            .satisfies(e -> assertThat(e.getDiabete()).as("check diabete").isEqualTo(actual.getDiabete()))
            .satisfies(e -> assertThat(e.getInsulinoDep()).as("check insulinoDep").isEqualTo(actual.getInsulinoDep()))
            .satisfies(e -> assertThat(e.getHypothyroidie()).as("check hypothyroidie").isEqualTo(actual.getHypothyroidie()))
            .satisfies(e -> assertThat(e.getAgeDecouverte()).as("check ageDecouverte").isEqualTo(actual.getAgeDecouverte()))
            .satisfies(e ->
                assertThat(e.getAutreEndocrinopathie()).as("check autreEndocrinopathie").isEqualTo(actual.getAutreEndocrinopathie())
            )
            .satisfies(e -> assertThat(e.getAutreAnomCong()).as("check autreAnomCong").isEqualTo(actual.getAutreAnomCong()))
            .satisfies(e -> assertThat(e.getDateNumSanguine()).as("check dateNumSanguine").isEqualTo(actual.getDateNumSanguine()))
            .satisfies(e -> assertThat(e.getAge()).as("check age").isEqualTo(actual.getAge()))
            .satisfies(e -> assertThat(e.getHb()).as("check hb").isEqualTo(actual.getHb()))
            .satisfies(e -> assertThat(e.getvGM()).as("check vGM").isEqualTo(actual.getvGM()))
            .satisfies(e -> assertThat(e.getRetic()).as("check retic").isEqualTo(actual.getRetic()))
            .satisfies(e -> assertThat(e.getLeuco()).as("check leuco").isEqualTo(actual.getLeuco()))
            .satisfies(e -> assertThat(e.getpNN()).as("check pNN").isEqualTo(actual.getpNN()))
            .satisfies(e -> assertThat(e.getPlq()).as("check plq").isEqualTo(actual.getPlq()))
            .satisfies(e -> assertThat(e.getHbInf()).as("check hbInf").isEqualTo(actual.getHbInf()))
            .satisfies(e -> assertThat(e.getPlqInf()).as("check plqInf").isEqualTo(actual.getPlqInf()))
            .satisfies(e -> assertThat(e.getpNNInf()).as("check pNNInf").isEqualTo(actual.getpNNInf()))
            .satisfies(e -> assertThat(e.getElectrophoreseHb()).as("check electrophoreseHb").isEqualTo(actual.getElectrophoreseHb()))
            .satisfies(e -> assertThat(e.getHbf()).as("check hbf").isEqualTo(actual.getHbf()))
            .satisfies(e -> assertThat(e.getMyelogramme()).as("check myelogramme").isEqualTo(actual.getMyelogramme()))
            .satisfies(e -> assertThat(e.getCellularite()).as("check cellularite").isEqualTo(actual.getCellularite()))
            .satisfies(e -> assertThat(e.getErythroblaste()).as("check erythroblaste").isEqualTo(actual.getErythroblaste()))
            .satisfies(e -> assertThat(e.getMorphologieEryth()).as("check morphologieEryth").isEqualTo(actual.getMorphologieEryth()))
            .satisfies(e -> assertThat(e.getMorphologieGran()).as("check morphologieGran").isEqualTo(actual.getMorphologieGran()))
            .satisfies(e -> assertThat(e.getMorphologieMega()).as("check morphologieMega").isEqualTo(actual.getMorphologieMega()))
            .satisfies(e -> assertThat(e.getGranuleux()).as("check granuleux").isEqualTo(actual.getGranuleux()))
            .satisfies(e -> assertThat(e.getDysmyelopoiese()).as("check dysmyelopoiese").isEqualTo(actual.getDysmyelopoiese()))
            .satisfies(e -> assertThat(e.getMegacaryocytes()).as("check megacaryocytes").isEqualTo(actual.getMegacaryocytes()))
            .satisfies(e -> assertThat(e.getBlaste()).as("check blaste").isEqualTo(actual.getBlaste()))
            .satisfies(e -> assertThat(e.getExcesblastes()).as("check excesblastes").isEqualTo(actual.getExcesblastes()))
            .satisfies(e -> assertThat(e.getbOM()).as("check bOM").isEqualTo(actual.getbOM()))
            .satisfies(e -> assertThat(e.getAdipocytes()).as("check adipocytes").isEqualTo(actual.getAdipocytes()))
            .satisfies(e -> assertThat(e.getUbiquitination()).as("check ubiquitination").isEqualTo(actual.getUbiquitination()))
            .satisfies(e -> assertThat(e.getResUbiquitination()).as("check resUbiquitination").isEqualTo(actual.getResUbiquitination()))
            .satisfies(e -> assertThat(e.getGroupComp()).as("check groupComp").isEqualTo(actual.getGroupComp()))
            .satisfies(e -> assertThat(e.getMutationFANC()).as("check mutationFANC").isEqualTo(actual.getMutationFANC()))
            .satisfies(e -> assertThat(e.getCongelationCellule()).as("check congelationCellule").isEqualTo(actual.getCongelationCellule()))
            .satisfies(e -> assertThat(e.getLabo()).as("check labo").isEqualTo(actual.getLabo()))
            .satisfies(e -> assertThat(e.getTypePrelevement()).as("check typePrelevement").isEqualTo(actual.getTypePrelevement()))
            .satisfies(e -> assertThat(e.getScoreClinique()).as("check scoreClinique").isEqualTo(actual.getScoreClinique()))
            .satisfies(e -> assertThat(e.getScoreEBMT()).as("check scoreEBMT").isEqualTo(actual.getScoreEBMT()))
            .satisfies(e -> assertThat(e.getScore()).as("check score").isEqualTo(actual.getScore()))
            .satisfies(e -> assertThat(e.getTransfusion()).as("check transfusion").isEqualTo(actual.getTransfusion()))
            .satisfies(e -> assertThat(e.getAgeTransf()).as("check ageTransf").isEqualTo(actual.getAgeTransf()))
            .satisfies(e -> assertThat(e.getDelaiDiag()).as("check delaiDiag").isEqualTo(actual.getDelaiDiag()))
            .satisfies(e -> assertThat(e.getNbCG()).as("check nbCG").isEqualTo(actual.getNbCG()))
            .satisfies(e -> assertThat(e.getNbCP()).as("check nbCP").isEqualTo(actual.getNbCP()))
            .satisfies(e -> assertThat(e.getChelationFer()).as("check chelationFer").isEqualTo(actual.getChelationFer()))
            .satisfies(e -> assertThat(e.getChelateur()).as("check chelateur").isEqualTo(actual.getChelateur()))
            .satisfies(e -> assertThat(e.getNilevar()).as("check nilevar").isEqualTo(actual.getNilevar()))
            .satisfies(e -> assertThat(e.getDanatrol()).as("check danatrol").isEqualTo(actual.getDanatrol()))
            .satisfies(e -> assertThat(e.getOxynethadone()).as("check oxynethadone").isEqualTo(actual.getOxynethadone()))
            .satisfies(e -> assertThat(e.getAndrotordyl()).as("check androtordyl").isEqualTo(actual.getAndrotordyl()))
            .satisfies(e -> assertThat(e.getAutreAndrogene()).as("check autreAndrogene").isEqualTo(actual.getAutreAndrogene()))
            .satisfies(e -> assertThat(e.getAndroDebut()).as("check androDebut").isEqualTo(actual.getAndroDebut()))
            .satisfies(e -> assertThat(e.getAndroFin()).as("check androFin").isEqualTo(actual.getAndroFin()))
            .satisfies(e -> assertThat(e.getObservance()).as("check observance").isEqualTo(actual.getObservance()))
            .satisfies(e -> assertThat(e.getToxicite()).as("check toxicite").isEqualTo(actual.getToxicite()))
            .satisfies(e -> assertThat(e.getAutreToxicite()).as("check autreToxicite").isEqualTo(actual.getAutreToxicite()))
            .satisfies(e -> assertThat(e.getEnqueteHLA()).as("check enqueteHLA").isEqualTo(actual.getEnqueteHLA()))
            .satisfies(e -> assertThat(e.getPourquoiEnqHLA()).as("check pourquoiEnqHLA").isEqualTo(actual.getPourquoiEnqHLA()))
            .satisfies(e -> assertThat(e.getNbFratTyp()).as("check nbFratTyp").isEqualTo(actual.getNbFratTyp()))
            .satisfies(e -> assertThat(e.getNbFratNTyp()).as("check nbFratNTyp").isEqualTo(actual.getNbFratNTyp()))
            .satisfies(e -> assertThat(e.getDonneurComp()).as("check donneurComp").isEqualTo(actual.getDonneurComp()))
            .satisfies(e -> assertThat(e.getPreciseDonneur()).as("check preciseDonneur").isEqualTo(actual.getPreciseDonneur()))
            .satisfies(e -> assertThat(e.getDonneur()).as("check donneur").isEqualTo(actual.getDonneur()))
            .satisfies(e -> assertThat(e.getGreffeFaite()).as("check greffeFaite").isEqualTo(actual.getGreffeFaite()))
            .satisfies(e -> assertThat(e.getDelaiRappDiag()).as("check delaiRappDiag").isEqualTo(actual.getDelaiRappDiag()))
            .satisfies(e -> assertThat(e.getPourquoiNfaite()).as("check pourquoiNfaite").isEqualTo(actual.getPourquoiNfaite()))
            .satisfies(e -> assertThat(e.getCyclophosphamide()).as("check cyclophosphamide").isEqualTo(actual.getCyclophosphamide()))
            .satisfies(e -> assertThat(e.getFludarabine()).as("check fludarabine").isEqualTo(actual.getFludarabine()))
            .satisfies(e -> assertThat(e.getBusulfan()).as("check busulfan").isEqualTo(actual.getBusulfan()))
            .satisfies(e -> assertThat(e.getDoseCyclo()).as("check doseCyclo").isEqualTo(actual.getDoseCyclo()))
            .satisfies(e -> assertThat(e.getDoseFlu()).as("check doseFlu").isEqualTo(actual.getDoseFlu()))
            .satisfies(e -> assertThat(e.getDoseBus()).as("check doseBus").isEqualTo(actual.getDoseBus()))
            .satisfies(e ->
                assertThat(e.getAutreConditionnement()).as("check autreConditionnement").isEqualTo(actual.getAutreConditionnement())
            )
            .satisfies(e -> assertThat(e.getIrradiation()).as("check irradiation").isEqualTo(actual.getIrradiation()))
            .satisfies(e -> assertThat(e.getDoseTotaleIrr()).as("check doseTotaleIrr").isEqualTo(actual.getDoseTotaleIrr()))
            .satisfies(e -> assertThat(e.getSerotherapie()).as("check serotherapie").isEqualTo(actual.getSerotherapie()))
            .satisfies(e -> assertThat(e.getsAL()).as("check sAL").isEqualTo(actual.getsAL()))
            .satisfies(e -> assertThat(e.getDoseSAL()).as("check doseSAL").isEqualTo(actual.getDoseSAL()))
            .satisfies(e -> assertThat(e.getSourceCellule()).as("check sourceCellule").isEqualTo(actual.getSourceCellule()))
            .satisfies(e -> assertThat(e.getSortieAplasie()).as("check sortieAplasie").isEqualTo(actual.getSortieAplasie()))
            .satisfies(e -> assertThat(e.getGradeaGvH()).as("check gradeaGvH").isEqualTo(actual.getGradeaGvH()))
            .satisfies(e -> assertThat(e.getcGvH()).as("check cGvH").isEqualTo(actual.getcGvH()))
            .satisfies(e -> assertThat(e.getmVO()).as("check mVO").isEqualTo(actual.getmVO()))
            .satisfies(e ->
                assertThat(e.getComplicationPulmonaire()).as("check complicationPulmonaire").isEqualTo(actual.getComplicationPulmonaire())
            )
            .satisfies(e -> assertThat(e.getPreciseCompPulm()).as("check preciseCompPulm").isEqualTo(actual.getPreciseCompPulm()))
            .satisfies(e -> assertThat(e.getSurvieJ100()).as("check survieJ100").isEqualTo(actual.getSurvieJ100()))
            .satisfies(e -> assertThat(e.getsMD()).as("check sMD").isEqualTo(actual.getsMD()))
            .satisfies(e -> assertThat(e.getAgeDiagSMD()).as("check ageDiagSMD").isEqualTo(actual.getAgeDiagSMD()))
            .satisfies(e -> assertThat(e.getCritereDiagSMD()).as("check critereDiagSMD").isEqualTo(actual.getCritereDiagSMD()))
            .satisfies(e -> assertThat(e.getTraitementSMD()).as("check traitementSMD").isEqualTo(actual.getTraitementSMD()))
            .satisfies(e -> assertThat(e.getlAM()).as("check lAM").isEqualTo(actual.getlAM()))
            .satisfies(e -> assertThat(e.getCritereDiagLAM()).as("check critereDiagLAM").isEqualTo(actual.getCritereDiagLAM()))
            .satisfies(e -> assertThat(e.getTraitementLAM()).as("check traitementLAM").isEqualTo(actual.getTraitementLAM()))
            .satisfies(e -> assertThat(e.getAutresCancers()).as("check autresCancers").isEqualTo(actual.getAutresCancers()))
            .satisfies(e -> assertThat(e.getdDN()).as("check dDN").isEqualTo(actual.getdDN()))
            .satisfies(e ->
                assertThat(e.getTransformationAigue()).as("check transformationAigue").isEqualTo(actual.getTransformationAigue())
            )
            .satisfies(e -> assertThat(e.getAgeDiagLA()).as("check ageDiagLA").isEqualTo(actual.getAgeDiagLA()))
            .satisfies(e -> assertThat(e.getTraitementLA()).as("check traitementLA").isEqualTo(actual.getTraitementLA()))
            .satisfies(e -> assertThat(e.getCancerE()).as("check cancerE").isEqualTo(actual.getCancerE()))
            .satisfies(e -> assertThat(e.getLocalisation()).as("check localisation").isEqualTo(actual.getLocalisation()))
            .satisfies(e -> assertThat(e.getTypeHistologique()).as("check typeHistologique").isEqualTo(actual.getTypeHistologique()))
            .satisfies(e -> assertThat(e.getTraitementCancer()).as("check traitementCancer").isEqualTo(actual.getTraitementCancer()))
            .satisfies(e -> assertThat(e.getPreciseTraitement()).as("check preciseTraitement").isEqualTo(actual.getPreciseTraitement()))
            .satisfies(e -> assertThat(e.getEvolutionCyto()).as("check evolutionCyto").isEqualTo(actual.getEvolutionCyto()))
            .satisfies(e -> assertThat(e.getFormuleChrom()).as("check formuleChrom").isEqualTo(actual.getFormuleChrom()))
            .satisfies(e -> assertThat(e.getAgeE()).as("check ageE").isEqualTo(actual.getAgeE()))
            .satisfies(e -> assertThat(e.getStatut()).as("check statut").isEqualTo(actual.getStatut()))
            .satisfies(e -> assertThat(e.getCauseDeces()).as("check causeDeces").isEqualTo(actual.getCauseDeces()))
            .satisfies(e -> assertThat(e.getAutreCauseD()).as("check autreCauseD").isEqualTo(actual.getAutreCauseD()))
            .satisfies(e -> assertThat(e.getSurvieGlobale()).as("check survieGlobale").isEqualTo(actual.getSurvieGlobale()))
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getDateMAJ()).as("check dateMAJ").isEqualTo(actual.getDateMAJ()))
            .satisfies(e -> assertThat(e.getNombreTacheCafe()).as("check nombreTacheCafe").isEqualTo(actual.getNombreTacheCafe()))
            .satisfies(e -> assertThat(e.getNombreTacheHypo()).as("check nombreTacheHypo").isEqualTo(actual.getNombreTacheHypo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFicheUpdatableRelationshipsEquals(Fiche expected, Fiche actual) {
        // empty method
    }
}
