package tn.tfar.fanconi.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LaboratoireAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLaboratoireAllPropertiesEquals(Laboratoire expected, Laboratoire actual) {
        assertLaboratoireAutoGeneratedPropertiesEquals(expected, actual);
        assertLaboratoireAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLaboratoireAllUpdatablePropertiesEquals(Laboratoire expected, Laboratoire actual) {
        assertLaboratoireUpdatableFieldsEquals(expected, actual);
        assertLaboratoireUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLaboratoireAutoGeneratedPropertiesEquals(Laboratoire expected, Laboratoire actual) {
        assertThat(expected)
            .as("Verify Laboratoire auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLaboratoireUpdatableFieldsEquals(Laboratoire expected, Laboratoire actual) {
        assertThat(expected)
            .as("Verify Laboratoire relevant properties")
            .satisfies(e -> assertThat(e.getNomLaboratoire()).as("check nomLaboratoire").isEqualTo(actual.getNomLaboratoire()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLaboratoireUpdatableRelationshipsEquals(Laboratoire expected, Laboratoire actual) {
        // empty method
    }
}
