import dayjs from 'dayjs/esm';

import { IFiche, NewFiche } from './fiche.model';

export const sampleWithRequiredData: IFiche = {
  id: 8946,
};

export const sampleWithPartialData: IFiche = {
  id: 22497,
  nDossier: 'replacer étant donné que de peur de',
  dateEnregistrement: dayjs('2025-05-12'),
  hopital: 32013,
  nbVivant: 18263,
  nbMort: 15133,
  avortement: 27249,
  cousin: 2112,
  enqueteFam: 'fourbe corps enseignant',
  typeCancer: 'rectangulaire',
  tailleNaiss: 19865.26,
  hypotrophie: 'glouglou',
  aAgeChDiag: 25467,
  aAgeOssDiag: 15497,
  poids: 11510.39,
  poidsDS: 'dès que avant que en dehors de',
  dOS: 'confondre soit',
  traitsFin: 'impromptu appartenir',
  autreAtTete: 'calmer',
  reinFerChev: 'hystérique',
  petitRein: 'chef',
  reinUnique: 'tellement fade',
  autreAnomVerge: 'touchant suivant ah',
  retardPubertaire: 'hé libérer absolument',
  mTanner: 'ouch trop',
  pTanner: 'patientèle',
  tTanner: 'ding areu areu',
  anomUrin: 'sur antagoniste',
  typeAnomUrin: 'par d’autant que',
  atteinteOss: 'comme boum',
  radiosfaites: 'céans piquer du côté de',
  surnumerarie: 'où',
  bifide: 'contester',
  aspectPouce: 'dehors refermer',
  autreAnomPouce: 'vétuste restreindre antique',
  anomAutDoigts: 'marier en decà de assez',
  syndactylie: 'avant',
  autreAnomDoigts: 'assurément afin de',
  anomalieos: 'près fidèle',
  agenesieRadius: 'clientèle quand biathlète',
  lCH: 'super',
  preciseAnomRac: 'dès',
  autreAnomOss: 'lectorat par rapport à',
  anomNeuro: 'pendant que membre du personnel',
  hypoacousie: 'si bien que placide',
  performanceScolaire: 'membre titulaire incognito',
  endocrinopathie: 'dans la mesure où dévoiler trop',
  hypothyroidie: 'debout gens',
  ageDecouverte: 9315,
  autreEndocrinopathie: 'timide',
  dateNumSanguine: dayjs('2025-05-11'),
  retic: 15082.23,
  pNN: 23364.68,
  plqInf: "déborder pêcher à l'égard de",
  erythroblaste: 19339.41,
  morphologieGran: 'inquiéter aïe',
  granuleux: 31091.02,
  dysmyelopoiese: 'clac',
  megacaryocytes: 'puisque bien que à demi',
  blaste: 25359.41,
  excesblastes: 'par rapport à au lieu de',
  adipocytes: 28552.57,
  ubiquitination: 'sans',
  groupComp: 'raccrocher adhérer',
  congelationCellule: 'énorme',
  labo: 'pschitt',
  scoreClinique: 2636,
  scoreEBMT: 4227,
  transfusion: 'lorsque ronron ouah',
  chelationFer: 'oups parlementaire',
  chelateur: 'suivant',
  nilevar: 'pff rester',
  androDebut: dayjs('2025-05-12'),
  androFin: dayjs('2025-05-12'),
  autreToxicite: 'pourvu que mélancolique triathlète',
  enqueteHLA: 'rapide à demi simple',
  pourquoiEnqHLA: 'biathlète concurrence aussitôt que',
  nbFratNTyp: 25229,
  donneurComp: 6779,
  preciseDonneur: 'à la faveur de splendide émérite',
  delaiRappDiag: 3584.81,
  doseCyclo: 8227.43,
  doseFlu: 12376.05,
  doseSAL: 31602.85,
  sourceCellule: 'turquoise au-dessous',
  gradeaGvH: 'maintenant prestataire de services',
  cGvH: 'sus émerger drôlement',
  mVO: 'dessus',
  preciseCompPulm: 'timide auprès de',
  traitementSMD: 'aventurer adepte clientèle',
  critereDiagLAM: 'patientèle perdre moderne',
  autresCancers: 'au-dessous de',
  dDN: dayjs('2025-05-12'),
  cancerE: 'areu areu ha ha aussitôt',
  localisation: 'lunatique selon quoique',
  traitementCancer: 'ouf beaucoup',
  ageE: 8454,
  autreCauseD: 'complètement réprimer',
  survieGlobale: 27605.69,
  nombreTacheHypo: 32421,
};

export const sampleWithFullData: IFiche = {
  id: 32540,
  nDossier: 'devant alors que',
  dateDiagnostic: dayjs('2025-05-11'),
  dateEnregistrement: dayjs('2025-05-12'),
  medecin: 'police zzzz moyennant',
  hopital: 8764,
  service: 9558,
  degConsang: 'près athlète sauvegarder',
  placeEnfant: 6164,
  nbVivant: 19126,
  nbMort: 24508,
  mortNe: 17332,
  avortement: 18166,
  cousin: 20962,
  membre: 27084,
  arbregenealogique: '../fake-data/blob/hipster.png',
  arbregenealogiqueContentType: 'unknown',
  arbregenealogiquecancer: '../fake-data/blob/hipster.png',
  arbregenealogiquecancerContentType: 'unknown',
  syndromeAnemique: 'badaboum aigre à côté de',
  syndromeHem: 'féliciter un peu si',
  syndromeInf: 'gens de par atchoum',
  decouverteFort: 'aimable espiègle',
  enqueteFam: 'pis commis de cuisine',
  typeCancer: 'tandis que',
  cancer: 'bang baiser',
  tailleNaiss: 2985.68,
  poidsNaiss: 4874.38,
  hypotrophie: 'parfois drôlement pff',
  troubleCroi: 'au-dessus de donner',
  aAgeChDiag: 11663,
  mAgeChDiag: 9465,
  aAgeOssDiag: 2884,
  mAgeOssDiag: 32528,
  ageRetard: 2900,
  poids: 26610.29,
  poidsDS: 'blême jusqu’à ce que spécialiste',
  taille: 3026.56,
  tailleDS: 'infime parlementaire',
  atteinteCut: 'vlan',
  tacheCaf: 'lâche chef de cuisine',
  ventre: 'assurément',
  membreSup: 'responsable manger',
  membreInf: 'chef de façon que',
  visage: 'bzzz inciter',
  thorax: 'présidence reprendre',
  dOS: 'rendre',
  hyperPig: 'fade dorénavant ha ha',
  hypochromique: 'tout trop',
  couleurPeau: 'aux environs de secouriste blablabla',
  autreAtCut: 'adepte violer aigre',
  atteinteTete: 'plus',
  microcephalie: 'de manière à ce que',
  microphtalmie: 'pour que séculaire clac',
  facieTrig: 'au point que en decà de',
  traitsFin: 'intégrer réagir',
  autreAtTete: 'avant',
  empreintedigitiforme: 'dans la mesure où rédaction',
  malUro: 'meuh',
  uIV: 'bè',
  echo: 'miam',
  reinEctop: "tchou tchouu d'avec",
  siegeEctopie: 'lécher dring brouiller',
  reinFerChev: 'commissionnaire membre du personnel',
  petitRein: 'applaudir',
  reinUnique: 'avant',
  ectopTest: 'personnel imiter',
  vergeInsuf: 'âcre même administration',
  autreAnomVerge: 'planquer calmer',
  retardPubertaire: 'croâ ferme',
  mTanner: 'cyan diplomate',
  pTanner: 'bien plouf ronron',
  tTanner: 'de sorte que vorace',
  anomUrin: 'proche de par rapport à tant',
  typeAnomUrin: 'suivant en dehors de',
  atteinteOss: 'énergique triathlète',
  radiosfaites: 'probablement contre aux alentours de',
  anomPouce: 'maintenant longtemps',
  surnumerarie: 'sous',
  agenesiePouce: 'touriste',
  bifide: 'en plus de si diététiste',
  hypoPouce: 'baiser',
  aspectPouce: 'administration passablement',
  hypoEminence: 'vaste si',
  absenceRadial: 'interrompre',
  pouceBas: 'tant que en decà de',
  autreAnomPouce: 'jusque ouf guide',
  anomAutDoigts: 'groin groin parce que imposer',
  courtstrapus: 'avex',
  syndactylie: 'lorsque',
  autreAnomDoigts: 'de sorte que',
  anomalieos: 'si bien que',
  agenesieRadius: 'intrépide invoquer',
  autreanomalieMembresup: 'entièrement',
  anomOrteil: 'examiner ah ramper',
  preciseAnomOrt: 'prout parce que sale',
  lCH: 'triathlète même si',
  autreanomalieMembreinf: 'bien que si',
  anomRachis: 'partenaire à force de miam',
  preciseAnomRac: 'tant payer animer',
  autreAnomOss: 'serviable gestionnaire',
  anomNeuro: 'négocier par suite de dedans',
  retardMent: 'membre du personnel quoique',
  hypoacousie: 'trop tendre personnel',
  strabisme: "à l'égard de lorsque gestionnaire",
  performanceScolaire: 'à cause de camarade',
  autreanomalieneurologique: 'au-dessous de timide quand',
  anomCardVas: 'équipe de recherche séculaire',
  echoCoeur: 'pour que',
  preciseAnomCardio: 'avant que simple délégation',
  anomDig: 'commis de cuisine trop trier',
  preciseAnomDig: 'à la faveur de',
  endocrinopathie: 'jeune enfant',
  diabete: 'pschitt collègue quasiment',
  insulinoDep: 'interpréter',
  hypothyroidie: 'diriger pour que',
  ageDecouverte: 26693,
  autreEndocrinopathie: 'pendant que terne',
  autreAnomCong: 'certes',
  dateNumSanguine: dayjs('2025-05-12'),
  age: 15447,
  hb: 14554.29,
  vGM: 9730.02,
  retic: 15035.01,
  leuco: 27580.46,
  pNN: 31206.24,
  plq: 2655.63,
  hbInf: 'badaboum police',
  plqInf: 'renforcer',
  pNNInf: 'assez avant que',
  electrophoreseHb: 'de crainte que vlan',
  hbf: 23194.22,
  myelogramme: 'toujours collègue diététiste',
  cellularite: 'après commis',
  erythroblaste: 20380.47,
  morphologieEryth: 'contre biathlète',
  morphologieGran: 'debout pff vorace',
  morphologieMega: 'commis de cuisine aux alentours de',
  granuleux: 3639.15,
  dysmyelopoiese: 'assez à seule fin de',
  megacaryocytes: 'dessous',
  blaste: 23131.42,
  excesblastes: 'pis minuscule',
  bOM: 'tsoin-tsoin',
  adipocytes: 19131.59,
  ubiquitination: 'défiler',
  resUbiquitination: 'du moment que ouah ouah',
  groupComp: 'snif au cas où',
  mutationFANC: 'dans',
  congelationCellule: 'adversaire changer à la faveur de',
  labo: 'tant',
  typePrelevement: 'dîner établir',
  scoreClinique: 20918,
  scoreEBMT: 30568,
  score: 'bof',
  transfusion: 'puisque à travers parce que',
  ageTransf: 26002,
  delaiDiag: 20719.19,
  nbCG: 'ici protester',
  nbCP: 'présidence de par informer',
  chelationFer: 'contre',
  chelateur: 'sans que en face de',
  nilevar: 'du moment que en dehors de vu que',
  danatrol: 'résoudre',
  oxynethadone: 'y égarer via',
  androtordyl: 'ensuite',
  autreAndrogene: 'entre tandis que',
  androDebut: dayjs('2025-05-12'),
  androFin: dayjs('2025-05-12'),
  observance: 'blême',
  toxicite: 'dépendre',
  autreToxicite: 'ah même si pourvu que',
  enqueteHLA: 'pour que',
  pourquoiEnqHLA: 'rectangulaire équilibrer brouiller',
  nbFratTyp: 30844,
  nbFratNTyp: 8850,
  donneurComp: 18315,
  preciseDonneur: 'hé candide chef',
  donneur: 'ouille',
  greffeFaite: 'concernant',
  delaiRappDiag: 3650.03,
  pourquoiNfaite: 'oh',
  cyclophosphamide: 'clientèle ensemble présidence',
  fludarabine: 'gratter tant équipe de recherche',
  busulfan: 'énorme',
  doseCyclo: 7023.65,
  doseFlu: 11789.93,
  doseBus: 1533.98,
  autreConditionnement: 'plouf équipe de recherche',
  irradiation: 'dedans contester gens',
  doseTotaleIrr: 19361.08,
  serotherapie: 'sauf calme bouffer',
  sAL: 'chef de cuisine miaou',
  doseSAL: 22510.2,
  sourceCellule: 'absolument exclure',
  sortieAplasie: 28752,
  gradeaGvH: 'corps enseignant commissionnaire jusque',
  cGvH: 'tantôt combien lorsque',
  mVO: 'désagréable concernant',
  complicationPulmonaire: 'à côté de',
  preciseCompPulm: 'pourpre désormais emprunter',
  survieJ100: 'contre',
  sMD: 'sage au-dessous',
  ageDiagSMD: 15509,
  critereDiagSMD: 'atchoum svelte de par',
  traitementSMD: 'au point que',
  lAM: 'comprendre même si blablabla',
  critereDiagLAM: 'administration insolite près de',
  traitementLAM: 'de façon à ce que cocorico lors de',
  autresCancers: 'bof ouf',
  dDN: dayjs('2025-05-11'),
  transformationAigue: 'insipide hystérique',
  ageDiagLA: 3304,
  traitementLA: 'contre secouriste avant de',
  cancerE: 'sans de manière à',
  localisation: 'freiner spécialiste après',
  typeHistologique: 'commissionnaire gens fusiller',
  traitementCancer: "parlementaire apte d'entre",
  preciseTraitement: 'souvent psitt éloigner',
  evolutionCyto: 'porte-parole depuis lors',
  formuleChrom: 'photographier après que',
  ageE: 4546,
  statut: 'dès que tchou tchouu avant',
  causeDeces: 'dans la mesure où ouah',
  autreCauseD: 'chut',
  survieGlobale: 22744.24,
  code: 16186,
  dateMAJ: dayjs('2025-05-12'),
  nombreTacheCafe: 22271,
  nombreTacheHypo: 23190,
};

export const sampleWithNewData: NewFiche = {
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
